// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlq_gpzI0JvF9vBPReG-IixrsLVZ8tJO0',
    appId: '1:524870970861:web:cb604e6b69e6d260358be4',
    messagingSenderId: '524870970861',
    projectId: 'final-task-univesity',
    authDomain: 'final-task-univesity.firebaseapp.com',
    storageBucket: 'final-task-univesity.firebasestorage.app',
    measurementId: 'G-1FJWP2366B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWViCJY3TvC4qdfgV2BgQ9VoDN4TsH4EQ',
    appId: '1:524870970861:android:c116b41b2917a54a358be4',
    messagingSenderId: '524870970861',
    projectId: 'final-task-univesity',
    storageBucket: 'final-task-univesity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTezbMvjq5JMNDyxVAYuS5ztJ4RszXLX4',
    appId: '1:524870970861:ios:8dc4b49b914716c1358be4',
    messagingSenderId: '524870970861',
    projectId: 'final-task-univesity',
    storageBucket: 'final-task-univesity.firebasestorage.app',
    iosBundleId: 'com.example.finalTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTezbMvjq5JMNDyxVAYuS5ztJ4RszXLX4',
    appId: '1:524870970861:ios:8dc4b49b914716c1358be4',
    messagingSenderId: '524870970861',
    projectId: 'final-task-univesity',
    storageBucket: 'final-task-univesity.firebasestorage.app',
    iosBundleId: 'com.example.finalTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlq_gpzI0JvF9vBPReG-IixrsLVZ8tJO0',
    appId: '1:524870970861:web:f3ca7e85b7909b16358be4',
    messagingSenderId: '524870970861',
    projectId: 'final-task-univesity',
    authDomain: 'final-task-univesity.firebaseapp.com',
    storageBucket: 'final-task-univesity.firebasestorage.app',
    measurementId: 'G-0BB6NJF8XT',
  );
}
